services:   
  aiprod_dev:
    container_name: aicore
    image: l4t_trt_image:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../../:/workspace/

    runtime: nvidia
    restart: unless-stopped

    environment:
      PYTHONIOENCODING: utf-8
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    stdin_open: true
    tty: true
    privileged: true
