services:   
  aiprod_dev:
    container_name: dstest
    image: ds_cont_arm:jnano-1.0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /media/sd64g/workspace:/workspace/

    runtime: nvidia
    restart: unless-stopped

    environment:
      PYTHONIOENCODING: utf-8
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    stdin_open: true
    tty: true
    privileged: true
